/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafile;
// Add your package declaration here, eg. package com.mycompany;
import static com.rollbar.notifier.config.ConfigBuilder.withAccessToken;
import com.rollbar.notifier.Rollbar;

public class App {
    public String getGreeting() {
        return "Hello Rollbar dashboard!";
    }

    public static void main(String[] args) throws Exception {
        // Add you class and method definitions
       // Within a method's body:
        Rollbar rollbar = Rollbar.init(withAccessToken("ADD-PROJECT-ACCESS-TOKEN")
                .environment("qa")
                .codeVersion("1.0.0")
                .build());
        rollbar.log("Hello, items dashboard.");

        Work w = new Work();
        w.printJobName();
//        rollbar.close(true);
        System.out.println(new App().getGreeting());
        w.Tests();
    }
}
